# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evolucao',
            old_name='sintomas',
            new_name='acao',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='evolucao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolucao_paciente', to='pacientes.Evolucao', verbose_name=b'Evolucao'),
        ),
    ]
