# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_auto_20171204_0002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='evolucao',
        ),
        migrations.AddField(
            model_name='evolucao',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evolucao_paciente', to='pacientes.Paciente', verbose_name=b'Paciente'),
        ),
    ]
