# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_auto_20171204_0142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evolucao',
            options={'verbose_name': 'Ocorr\xeancia em:', 'verbose_name_plural': 'Evolu\xe7\xf5es'},
        ),
        migrations.AlterModelOptions(
            name='paciente',
            options={'verbose_name': 'Paciente', 'verbose_name_plural': 'Pacientes'},
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='hospital',
        ),
        migrations.AddField(
            model_name='paciente',
            name='queixa',
            field=models.CharField(blank=True, help_text=b'', max_length=255, null=True, verbose_name=b'Queixa principal'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='sintomas',
            field=models.TextField(blank=True, help_text=b'', null=True, verbose_name=b'Sintomas apresentados'),
        ),
    ]
